export const ADD_NUMBER = 'ADD_NUMBER'
export const SUBTRACTION_NUMBER = 'SUBTRACTION_NUMBER'
export const INCREMENT_NUMBER = 'INCREMENT_NUMBER'
export const DECREMENT_NUMBER = 'DECREMENT_NUMBER'

export const CHANGE_BANNERS = 'CHANGE_BANNERS'
export const CHANGE_RECOMMENDS = 'CHANGE_RECOMMENDS'
